#!/bin/bash
while :; do osrm-routed -p 5001 /home/ssd/osrm/bicycle/bigslovakia.osrm > /dev/null; done &
while :; do osrm-routed -p 5000 /home/ssd/osrm/foot/bigslovakia.osrm > /dev/null ; done  &
while :; do osrm-routed -p 5002 /home/ssd/osrm/test/bratislava.osrm > /dev/null; done &
